# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nCS4CUYSKG0nezHxPgvYUwlY5aFRGWbw
"""

classifier_url ="https://hub.tensorflow.google.cn/google/tf2-preview/mobilenet_v2/classification/2"

import tensorflow as tf
import tensorflow_hub as hub
import numpy as np

from PIL import Image
from pathlib import Path

classifier_url ="https://hub.tensorflow.google.cn/google/tf2-preview/mobilenet_v2/classification/2"

IMAGE_SHAPE = (224, 224)

classifier = tf.keras.Sequential([
    hub.KerasLayer(classifier_url, input_shape=IMAGE_SHAPE+(3,))
])

img_dir = Path('data')
img_file = 'hum1.jpg'
img_path = img_dir / img_file
img_dir.exists()

img = Image.open(img_path).resize((224, 224))
img

img_data = np.array(img)/255.0
img_data.shape

result = classifier.predict(img_data[np.newaxis, ...])

result.shape

predicted_class = np.argmax(result[0], axis=-1)

predicted_class

result[0, predicted_class]

labels_path = tf.keras.utils.get_file('ImageNetLabels.txt','https://storage.googleapis.com/download.tensorflow.org/data/ImageNetLabels.txt')
imagenet_labels = np.array(open(labels_path).read().splitlines())

imagenet_labels[predicted_class]

